### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by pdehaan** [Masquerade-Circus/micro-ex-router#1]
Not sure if I'm using something wrong, or if I need to add some extra dependencies, but this is the error I get when I try and run the sample from the README.md file:

> _"ReferenceError: regeneratorRuntime is not defined"_

---

```sh
$ cat package.json
{
  "name": "micro-router-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index"
  },
  "author": "Peter deHaan <peter@deseloper.com> (https://about.me/peterdehaan)",
  "license": "WTFPL",
  "dependencies": {
    "micro": "7.3.3",
    "micro-ex-router": "1.1.0"
  }
}
```

```sh
$ cat index.js
let micro = require('micro');
let Router = require('micro-ex-router');

// Create a new router
let router = Router();

router
    // Use middlewares available to all routes
    .use((req, res) => console.log(req.url))

    // Default returned responses
    .get('/', () => 'Welcome to micro')

    // Parametrized paths
    .get('/hello/:world', (req, res) => ({message: `Hello ${req.params.world}`}))

    // Sequenced middlewares no need to use next callback,
    // All middlewares are processed as async
    // The first returned response will be sent to the client
    .get('/hello/:world/whats/:up', [
        (req, res) => {
            res.locals = {};
            res.locals.response = {message: `Hello ${req.params.world} whats ${req.params.up}`};
        },
        (req, res) => {
            return res.locals.response;
        }
    ])

    // Default parsed body for all methods other than get
    // Based on the Content-Type parses json, formurlencoded, text and and buffer
    .post('/hello', () => req.body)

    // Default parsed query parameters
    // if you call /hello/with/params?hello=world
    // then req.query = {hello: "world"}
    .get('/hello/with/params', () => req.query)
;

// Init micro server
let server = micro(router);

server.listen(3000, () => console.log('Micro listening on port 3000'));
```

```sh
$ npm start

> micro-router-test@1.0.0 start /Users/pdehaan/dev/tmp/del/micro-router-test
> node index

/Users/pdehaan/dev/tmp/del/micro-router-test/node_modules/micro-ex-router/dist/index.js:4137
        var _ref = asyncToGenerator(regeneratorRuntime.mark(function _callee(req, res) {
                                    ^

ReferenceError: regeneratorRuntime is not defined
    at /Users/pdehaan/dev/tmp/del/micro-router-test/node_modules/micro-ex-router/dist/index.js:4137:37
    at RouterFactory (/Users/pdehaan/dev/tmp/del/micro-router-test/node_modules/micro-ex-router/dist/index.js:4266:6)
    at Object.<anonymous> (/Users/pdehaan/dev/tmp/del/micro-router-test/index.js:5:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! micro-router-test@1.0.0 start: `node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the micro-router-test@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pdehaan/.npm/_logs/2017-07-09T22_43_34_430Z-debug.log
```

```sh
$ npm version
{ 'micro-router-test': '1.0.0',
  npm: '5.0.3',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  node: '8.1.2',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.12.0',
  v8: '5.8.283.41',
  zlib: '1.2.11' }
```

**Comment by zhaoyao91** [comment]
I face the same problem too

**Comment by Masquerade-Circus** [comment]
This problem was because I assumed the use of babel to transpile es6 modules to es5.
I have updated the build and added some examples of use.
I hope you can check them out.
